### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mdrezak** [Mahdiar-Vaez/react-project-shopping-shoes#2]
# پروژه بسیار خوبی هست. یکسری پیشنهاداتی که برای دوست عزیزم واعظ   داشتم جهت توسعه مهارت ها 🥇.

[اصول کد تمیز -  Clean code principles] (https://blog.asax.ir/clean-code-in-functions/)
[clean code in raect] (https://dev.to/serifcolakel/best-practices-for-writing-clean-react-code-with-examples-4b90)
> [!TIP]
> در پروژه شما اصل Dry تا حدودی نقض شده و بهتر بود برخی از کامپوننت ها به کامپوننت های کوچکتری تقسیم میشدند 
## برای مثال : 
``` navItem.jsx ```
```jsx
function navItem({ link, icon, text }) {
  return (
    <Link to={link}>
            <Button
              startIcon={icon}
              sx={{
                height: "50px",
              }}
              size="small"
              variant="text"
              color="primary"
            >
              text 
            </Button>
          </Link>
  );
}
```
و در نهایت کد ``` /Navbar/index.jsx ``` میشد یه همچین چیزی  
```jsx
...
export default function Navbar() {
...
    return (
     ...
     <navItem  link="/UrlToSomeThings" icon="{<InventoryIcon/>}" text="SomeText"/>
     <navItem  link="/UrlToSomeThings" icon="{<InventoryIcon/>}" text="SomeText"/>
     <navItem  link="/UrlToSomeThings" icon="{<InventoryIcon/>}" text="SomeText"/>
     <navItem  link="/UrlToSomeThings" icon="{<InventoryIcon/>}" text="SomeText"/>
     ...
    );
}
```

امیدوارم در طول زندگیت همیشه موفق و پیروز باشی.  (از دوست رفیق و همکلاسی محمدرضا کریمانی 1402/12/26)

**Comment by Mahdiar-Vaez** [comment]
سلام بر کریمانی عزیز
در واقع استفاده از  کامپوننت لینک اجباری است زیرا از ریاکت  روتر دام برای
اس پی ای بودن است و در صورت استفاده نکردن سایت اس پی ای نمیشود
و navitem شما هم از بوتسترپ هست ولی من از م یو ای استفاده میکردم برای همین
چنین چیزی امکان پذیر نیست
شما هم تا حدودی درست میگویید حتی من می‌توانستم  از فایل سی اس اس جداگانه
استفاده کنم ولی از ساخت فایل اضافه خودداری کردم

**Comment by Mahdiar-Vaez** [comment]
در واقع استفاده از کامپوننت Button به خاطر تمیزی دکمه هایی است که از ام یو
آی ایمپورت کردم

بسیار ممنون
